name: Pylint and run

on: [push]

jobs:
  build:

    runs-on: [self-hosted, linux, x64]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint 
        pip install pyenchant
    - name: Analysing the code with pylint
      run: |
        find . -name '*.py' -exec pylint {} \;
        pylint $(git ls-files '*.py')
    - name: give me some words
      run: |
        python3 wordgen.py
